### ISSUE TITLE
Respect additional column/field "Kategorie"

### ISSUE THREAD

**Issue by riker09** [fabolhak/ofxstatement-de-ing#1]
I've activated the analysis feature in the Ing DiBa web interface to get an easy overview over my expenses. This adds a new column to the CSV export, labeled `Kategorie`. Due to the hard-wired columns this breaks the parsing. I will try to create a PR for this, but my Python skills are low and maybe you will beat me to this? ;)

**Comment by fabolhak** [comment]
Sorry for the late reply. Unfortunately, I was quite busy in the last months. I updated the plugin and hopefully made it more robust. Should now be able to handle extra columns (like category).
